# -*- coding: utf-8 -*-
"""EstudioMicroemprendimientos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KEC-Lle9RSfXWHmqHnAqHtG92rMW84L
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ruta_archivo = '/content/Base de Datos Full - VIII EME CSV.csv'
df = pd.read_csv(ruta_archivo, low_memory=False)

"""Exploración"""

df.head()

df.info()

df.describe()